// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/storage (interfaces: IStorage)
//
// Generated by this command:
//
//	mockgen -destination internal/mocks/mock_dbstorage.go -package mocks ./internal/repository/storage IStorage
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	types "github.com/kirillshkro/gshortener/internal/types"
	model "github.com/kirillshkro/gshortener/internal/types/model"
	gomock "go.uber.org/mock/gomock"
)

// MockIStorage is a mock of IStorage interface.
type MockIStorage struct {
	ctrl     *gomock.Controller
	recorder *MockIStorageMockRecorder
	isgomock struct{}
}

// MockIStorageMockRecorder is the mock recorder for MockIStorage.
type MockIStorageMockRecorder struct {
	mock *MockIStorage
}

// NewMockIStorage creates a new mock instance.
func NewMockIStorage(ctrl *gomock.Controller) *MockIStorage {
	mock := &MockIStorage{ctrl: ctrl}
	mock.recorder = &MockIStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStorage) EXPECT() *MockIStorageMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockIStorage) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockIStorageMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockIStorage)(nil).Close))
}

// Create mocks base method.
func (m *MockIStorage) Create(urlOriginalURL model.URLData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", urlOriginalURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIStorageMockRecorder) Create(urlOriginalURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIStorage)(nil).Create), urlOriginalURL)
}

// GetUserURLs mocks base method.
func (m *MockIStorage) GetUserURLs(userUUID string) ([]types.UserURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserURLs", userUUID)
	ret0, _ := ret[0].([]types.UserURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserURLs indicates an expected call of GetUserURLs.
func (mr *MockIStorageMockRecorder) GetUserURLs(userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserURLs", reflect.TypeOf((*MockIStorage)(nil).GetUserURLs), userUUID)
}

// OriginalURL mocks base method.
func (m *MockIStorage) OriginalURL(key types.ShortURL) (types.RawURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OriginalURL", key)
	ret0, _ := ret[0].(types.RawURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OriginalURL indicates an expected call of OriginalURL.
func (mr *MockIStorageMockRecorder) OriginalURL(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OriginalURL", reflect.TypeOf((*MockIStorage)(nil).OriginalURL), key)
}
