// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/storage (interfaces: IStorage)
//
// Generated by this command:
//
//	mockgen -destination internal/mocks/mock_dbstorage.go -package mocks ./internal/repository/storage IStorage
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	types "github.com/kirillshkro/gshortener/internal/types"
	gomock "go.uber.org/mock/gomock"
)

// MockIStorage is a mock of IStorage interface.
type MockIStorage struct {
	ctrl     *gomock.Controller
	recorder *MockIStorageMockRecorder
	isgomock struct{}
}

// MockIStorageMockRecorder is the mock recorder for MockIStorage.
type MockIStorageMockRecorder struct {
	mock *MockIStorage
}

// NewMockIStorage creates a new mock instance.
func NewMockIStorage(ctrl *gomock.Controller) *MockIStorage {
	mock := &MockIStorage{ctrl: ctrl}
	mock.recorder = &MockIStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStorage) EXPECT() *MockIStorageMockRecorder {
	return m.recorder
}

// Data mocks base method.
func (m *MockIStorage) Data(key types.ShortURL) (types.RawURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Data", key)
	ret0, _ := ret[0].(types.RawURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Data indicates an expected call of Data.
func (mr *MockIStorageMockRecorder) Data(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Data", reflect.TypeOf((*MockIStorage)(nil).Data), key)
}

// SetData mocks base method.
func (m *MockIStorage) SetData(reqData types.URLData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetData", reqData)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetData indicates an expected call of SetData.
func (mr *MockIStorageMockRecorder) SetData(reqData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetData", reflect.TypeOf((*MockIStorage)(nil).SetData), reqData)
}
