package main

import (
	"fmt"
	"go/ast"
	"log"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/tools/go/packages"
)

func main() {
	rootDir := os.Args[1]
	if rootDir == "" {
		log.Fatal("Введите директорию для сканирования пакета")
	}

	pkgs, err := findPackages(rootDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Ошибка при сканировании пакетов: %v\n", err)
		os.Exit(1)
	}

	for _, pkgPath := range pkgs {
		if err := processPackage(pkgPath); err != nil {
			fmt.Fprintf(os.Stderr, "Ошибка при обработке пакета %s: %v\n", pkgPath, err)
			os.Exit(1)
		}
	}
}

func findPackages(rootDir string) ([]string, error) {
	var packages []string

	err := filepath.Walk(rootDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		if !info.IsDir() {
			return nil
		}

		if isVendorDir(path) || isGeneratedDir(path) {
			return filepath.SkipDir
		}

		goFiles, err := filepath.Glob(filepath.Join(path, "*.go"))
		if err != nil {
			return err
		}

		if len(goFiles) > 0 {
			pkgName, err := getPackageName(path)
			if err != nil {
				return err
			}
			if pkgName != "" && pkgName != "main" {
				packages = append(packages, path)
			}
		}

		return nil
	})

	return packages, err
}

func isVendorDir(path string) bool {
	return strings.Contains(path, "/vendor/") || strings.HasSuffix(path, "/vendor")
}

func isGeneratedDir(path string) bool {
	return strings.Contains(path, "/.git")
}

func getPackageName(dir string) (string, error) {
	cfg := &packages.Config{
		Dir:  dir,
		Mode: packages.NeedName,
	}
	pkgs, err := packages.Load(cfg, ".")
	if err != nil {
		return "", err
	}

	if len(pkgs) > 0 && len(pkgs[0].Syntax) > 0 {
		return pkgs[0].Name, nil
	}

	return "", nil
}

func processPackage(pkgPath string) error {
	cfg := &packages.Config{
		Dir:  pkgPath,
		Mode: packages.NeedName | packages.NeedSyntax,
	}
	pkgs, err := packages.Load(cfg, ".")
	if err != nil {
		return fmt.Errorf("ошибка загрузки пакета: %w", err)
	}

	var generatedMethods []string

	for _, pkg := range pkgs {
		for _, file := range pkg.Syntax {
			ast.Inspect(file, func(n ast.Node) bool {
				decl, ok := n.(*ast.TypeSpec)
				if !ok {
					return true
				}

				_, ok = decl.Type.(*ast.StructType)
				if !ok {
					return true
				}

				if hasGenerateResetComment(decl.Doc) {
					method := generateResetMethod(decl.Name.Name)
					generatedMethods = append(generatedMethods, method)
				}

				return true
			})
		}
	}

	if len(generatedMethods) > 0 {
		return writeResetFile(pkgPath, generatedMethods)
	}

	return nil
}

func hasGenerateResetComment(comments *ast.CommentGroup) bool {
	if comments == nil {
		return false
	}

	for _, comment := range comments.List {
		if strings.TrimSpace(comment.Text) == "// generate:reset;" {
			return true
		}
	}

	return false
}

func generateResetMethod(structName string) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("// Reset%s сбрасывает все поля структуры %s к значениям по умолчанию\n", structName, structName))
	sb.WriteString(fmt.Sprintf("func (s *%s) Reset%s() {\n", structName, structName))
	sb.WriteString("}\n\n")

	return sb.String()
}

func writeResetFile(pkgPath string, methods []string) error {
	content := "// Code generated by reset tool. DO NOT EDIT.\n\npackage " + filepath.Base(pkgPath) + "\n\n"

	for _, method := range methods {
		content += method
	}

	resetFilePath := filepath.Join(pkgPath, "reset.gen.go")

	return os.WriteFile(resetFilePath, []byte(content), 0644)
}
