package main

import (
	"fmt"
	"go/ast"
	"os"
	"path/filepath"
	"strings"
)

// generateResetMethod генерирует тело метода Reset() для указанной структуры.
// Файл file используется для получения информации о полях структуры.
func generateResetMethod(structName string, file *ast.File) string {
	var sb strings.Builder

	fmt.Fprintf(&sb, "// Reset%s сбрасывает все поля структуры %s к значениям по умолчанию\n", structName, structName)
	fmt.Fprintf(&sb, "func (s *%s) Reset%s() {\n", structName, structName)

	if file != nil {
		ast.Inspect(file, func(n ast.Node) bool {
			decl, ok := n.(*ast.TypeSpec)
			if !ok {
				return true
			}

			if decl.Name.Name != structName {
				return true
			}

			structType, ok := decl.Type.(*ast.StructType)
			if !ok {
				return true
			}

			for _, field := range structType.Fields.List {
				if len(field.Names) == 0 {
					continue
				}

				fieldName := field.Names[0].Name
				fieldValue := generateResetFieldValue(field.Type)
				fmt.Fprintf(&sb, "\ts.%s = %s\n", fieldName, fieldValue)
			}

			return false
		})
	}

	sb.WriteString("}\n\n")

	return sb.String()
}

// generateResetFieldValue генерирует выражение для сброса значения поля к нулевому значению.
func generateResetFieldValue(node ast.Node) string {
	switch v := node.(type) {
	case *ast.Ident:
		return getZeroValue(v.Name)
	case *ast.StarExpr:
		return fmt.Sprintf("&%s{}", getZeroValueExpr(v.X))
	case *ast.ArrayType:
		elemType := generateResetFieldValue(v.Elt)
		return fmt.Sprintf("%s[:0]", elemType)
	case *ast.MapType:
		keyType := generateResetFieldValue(v.Key)
		valType := generateResetFieldValue(v.Value)
		return fmt.Sprintf("map[%s]%s{}", keyType, valType)
	case *ast.SelectorExpr:
		if ident, ok := v.X.(*ast.Ident); ok {
			return fmt.Sprintf("&%s{}", ident.Name)
		}
		return "nil"
	case *ast.ParenExpr:
		return generateResetFieldValue(v.X)
	default:
		return "nil"
	}
}

// getZeroValueExpr извлекает строковое представление типа для создания нулевого значения.
func getZeroValueExpr(node ast.Node) string {
	switch v := node.(type) {
	case *ast.Ident:
		return getZeroValue(v.Name)
	case *ast.StarExpr:
		return getZeroValueExpr(v.X)
	case *ast.SelectorExpr:
		if ident, ok := v.X.(*ast.Ident); ok {
			return ident.Name
		}
		return ""
	default:
		return ""
	}
}

// getZeroValue возвращает строковое представление нулевого значения для примитивного типа.
func getZeroValue(ty string) string {
	switch ty {
	case "string":
		return `""`
	case "bool":
		return "false"
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
		"float32", "float64",
		"complex64", "complex128":
		return "0"
	default:
		return fmt.Sprintf("&%s{}", ty)
	}
}

// writeResetFile записывает все сгенерированные методы в файл reset.go
// в той же директории, где находится пакет.
func writeResetFile(pkgPath string, methods []string) error {
	content := "// Code generated by reset tool. DO NOT EDIT.\n\npackage " + filepath.Base(pkgPath) + "\n\n"

	for _, method := range methods {
		content += method
	}

	resetFilePath := filepath.Join(pkgPath, "reset.go")

	return os.WriteFile(resetFilePath, []byte(content), 0644)
}

// Resetable интерфейс для типов, имеющих метод Reset()
type Resetable interface {
	Reset()
}

// Pool пул объектов с методом Reset()
type Pool[T Resetable] struct {
	pool []T
}

// New создает и возвращает указатель на структуру Pool
func New[T Resetable]() *Pool[T] {
	return &Pool[T]{}
}

// Get возвращает объект из пула
func (p *Pool[T]) Get() T {
	if len(p.pool) == 0 {
		var zero T
		return zero
	}
	obj := p.pool[len(p.pool)-1]
	p.pool = p.pool[:len(p.pool)-1]
	return obj
}

// Put помещает объект в пул
func (p *Pool[T]) Put(obj T) {
	obj.Reset()
	p.pool = append(p.pool, obj)
}
